eureka-config:
  url: http://localhost:8761/eureka
  lable: dev
mysql-config:
  url: jdbc:mysql://localhost:3306/troop-warehouse-management-system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
  username: root
  password: 123456
  lable: dev
gateway-config:
  url: http://localhost:7999
